### ISSUE TITLE
CVA market map

### ISSUE THREAD

**Issue by JonathanGarro** [Surge-Information-Management-Support/2024-bra-floods#14]
- **What**: Map of social vulnerability in Porto Alegre.
- **Outcome**: A map highlighting stores/shops/hubs with cultural significance to three groups in the Porto Alegre metro area: Afro-Descent, Indigenous, Migrant/Refugee.
- **Format**: A0 and digital
- **Priority**: Medium
- **Deadline**: Thursday, June 20
- **Link on GitHub**: [View issue](https://github.com/orgs/Surge-Information-Management-Support/projects/10/views/1?pane=issue&itemId=67679435)
- **Data Source**: D03 in operational Dropbox
- **Requestor**: Jeff Paddock, CVA Coordinator

**Comment by FrancescaAlba** [comment]
[BRA_Cambio houses - Sarandi area - Secondary points - v2.2.pdf](https://github.com/user-attachments/files/16366117/BRA_Cambio.houses.-.Sarandi.area.-.Secondary.points.-.v2.2.pdf)



[BRA_Cambio houses.pdf](https://github.com/user-attachments/files/16366149/BRA_Cambio.houses.pdf)



[FINALES MG B2C Locations - map points.zip](https://github.com/user-attachments/files/16366141/FINALES.MG.B2C.Locations.-.map.points.zip)
[MG Active Agents Brazil May 2024.zip](https://github.com/user-attachments/files/16366142/MG.Active.Agents.Brazil.May.2024.zip)
