### ISSUE TITLE
Distribution and affected area map

### ISSUE THREAD

**Issue by JonathanGarro** [Surge-Information-Management-Support/2024-bra-floods#15]
- **What**: Distributions map
- **Outcome**: A map that can visualize the products distributed by area and highlight the affected regions (see list of regions below)
- **Format**: Digital landscape
- **Priority**: High
- **Deadline**: Sunday, June 23
- **Link on GitHub**: [View issue](https://github.com/orgs/Surge-Information-Management-Support/projects/10?pane=issue&itemId=68147859)
- **Data Source**: D04 in operational Dropbox
- **Requestor**: Ops Manager

**Affected areas**
- Porto Alegre
- Canoas
- Guaiba
- Eldorado do Sul
- Novo Hamburgo
- Santa Barbara
- Santa Teresa
- Mucum
- Encantado
- Rocas Sales
- Colinas
- Arroio do Meio
- Lajeado
- Cruzeiro do Sul
- Estrela
- Taquari
- Bento Goncalves
- Cotipora dam
- Garibaldi
- Santa Tereza
- Pareci Novo
- Sao Vendelino
- Vale Real
- Sao Sebastiao do Cai
- Montenegro

**Comment by jeanne-crump** [comment]
hey @dmccorm1 could you give me an estimated day you think this will be updated? The operation is asking for it so just want to give them a timeline. Thanks!
