### ISSUE TITLE
XLS form for household survey

### ISSUE THREAD

**Issue by jeanne-crump** [Surge-Information-Management-Support/2024-bra-floods#21]
What: Develop XLS form to build a Kobo survey using existing questionnaire
Outcome: Have an XLS form ready to be uploaded to Kobo for a household survey
Format: Digital
Priority: High
Deadline: July 18th evening
Link on GitHub: [View issue](https://github.com/orgs/Surge-Information-Management-Support/projects/10/views/1?pane=issue&itemId=63987088)
Data Source:  P11 folder in Dropbox

**Comment by Katbaloo** [comment]
@jeanne-crump 

Initial questions:

- Do they want all non integer questions to be open text?
- are there estado, UF, municipio, and Bairro pick lists that should be used (or also leave open text?)

**Comment by Katbaloo** [comment]
First draft for review/feedbacks:

[v1_coleta de informações familiares.xlsx](https://github.com/user-attachments/files/16273024/v1_coleta.de.informacoes.familiares.xlsx)
